version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: aibos-postgres
    environment:
      POSTGRES_USER: ${DB_USER:-aibos}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-aibos_password}
      POSTGRES_DB: ${DB_NAME:-aibos_engine}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./packages/database/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-aibos}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: aibos-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: 